// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'sales_order_data_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_SalesOrderDataModel _$$_SalesOrderDataModelFromJson(
        Map<String, dynamic> json) =>
    _$_SalesOrderDataModel(
      salesTransactionId: json['sales_transaction_id'] as String?,
      locationId: json['location_id'] as String?,
      status: json['status'] as String?,
      invoiceNo: json['invoice_no'] as String?,
      transactionDate: json['transaction_date'] as String?,
      dueDate: json['due_date'] as String?,
      customerId: json['customer_id'] as String?,
      customerName: json['customer_name'] as String?,
      totalQty: json['total_qty'] as String?,
      totalAmount: json['total_amount'] as String?,
      totalDiscountId: json['total_discount_id'] as String?,
      totalDiscountPct: json['total_discount_pct'] as String?,
      totalDiscount: json['total_discount'] as String?,
      totalTax: json['total_tax'] as String?,
      courierId: json['courier_id'] as String?,
      shippingPrice: json['shipping_price'] as String?,
      totalExpense: json['total_expense'] as String?,
      totalCost: json['total_cost'] as String?,
      salesId: json['sales_id'] as String?,
      cashierName: json['cashier_name'] as String?,
      remark: json['remark'] as String?,
      paymentTypeId: json['payment_type_id'] as String?,
      paymentTermId: json['payment_term_id'] as String?,
      printTimes: json['print_times'] as String?,
      paidAmount: json['paid_amount'] as String?,
      roundingAmount: json['rounding_amount'] as String?,
      paymentAmount: json['payment_amount'] as String?,
      changeAmount: json['change_amount'] as String?,
      currencyId: json['currency_id'] as String?,
      currencyRate: json['currency_rate'] as String?,
      shipTo: json['ship_to'] as String?,
      fobId: json['fob_id'] as String?,
      isTaxable: json['is_taxable'] as String?,
      isInclusiveTax: json['is_inclusive_tax'] as String?,
      paymentDate: json['payment_date'] as String?,
      paymentStatus: json['payment_status'] as String?,
      freightAccountId: json['freight_account_id'] as String?,
      fiscalRate: json['fiscal_rate'] as String?,
      sourceTransId: json['source_trans_id'] as String?,
      invoiceDiscAccId: json['invoice_disc_acc_id'] as String?,
      isInclusiveFreight: json['is_inclusive_freight'] as String?,
      cancelBy: json['cancel_by'] as String?,
      cancelDate: json['cancel_date'] as String?,
      isPosTrans: json['is_pos_trans'] as String?,
      deliveryDate: json['delivery_date'] as String?,
      freightNo: json['freight_no'] as String?,
    );

Map<String, dynamic> _$$_SalesOrderDataModelToJson(
        _$_SalesOrderDataModel instance) =>
    <String, dynamic>{
      'sales_transaction_id': instance.salesTransactionId,
      'location_id': instance.locationId,
      'status': instance.status,
      'invoice_no': instance.invoiceNo,
      'transaction_date': instance.transactionDate,
      'due_date': instance.dueDate,
      'customer_id': instance.customerId,
      'customer_name': instance.customerName,
      'total_qty': instance.totalQty,
      'total_amount': instance.totalAmount,
      'total_discount_id': instance.totalDiscountId,
      'total_discount_pct': instance.totalDiscountPct,
      'total_discount': instance.totalDiscount,
      'total_tax': instance.totalTax,
      'courier_id': instance.courierId,
      'shipping_price': instance.shippingPrice,
      'total_expense': instance.totalExpense,
      'total_cost': instance.totalCost,
      'sales_id': instance.salesId,
      'cashier_name': instance.cashierName,
      'remark': instance.remark,
      'payment_type_id': instance.paymentTypeId,
      'payment_term_id': instance.paymentTermId,
      'print_times': instance.printTimes,
      'paid_amount': instance.paidAmount,
      'rounding_amount': instance.roundingAmount,
      'payment_amount': instance.paymentAmount,
      'change_amount': instance.changeAmount,
      'currency_id': instance.currencyId,
      'currency_rate': instance.currencyRate,
      'ship_to': instance.shipTo,
      'fob_id': instance.fobId,
      'is_taxable': instance.isTaxable,
      'is_inclusive_tax': instance.isInclusiveTax,
      'payment_date': instance.paymentDate,
      'payment_status': instance.paymentStatus,
      'freight_account_id': instance.freightAccountId,
      'fiscal_rate': instance.fiscalRate,
      'source_trans_id': instance.sourceTransId,
      'invoice_disc_acc_id': instance.invoiceDiscAccId,
      'is_inclusive_freight': instance.isInclusiveFreight,
      'cancel_by': instance.cancelBy,
      'cancel_date': instance.cancelDate,
      'is_pos_trans': instance.isPosTrans,
      'delivery_date': instance.deliveryDate,
      'freight_no': instance.freightNo,
    };
